from app.extensions import db


class BarangayMonthlyHistory(db.Model):
    """One row per barangay per calendar month: the food packs that were
    needed / distributed that month. This is the time series the SARIMAX
    forecaster (app.ml.train) is fitted on.

    data_source says where a row came from, so real records can be told apart
    from stand-in data and swapped in without touching the model code:
      'synthetic'   - generated by scripts/seed_monthly_history.py from the
                      real 2021-2025 storm calendar + PAGASA climatology
      'real_sample' - transcribed from an official relief-distribution sheet
                      (e.g. Sta. Barbara, Aug 2026)
      'system'      - rolled up from this system's own allocation records
    """
    __tablename__ = "barangay_monthly_history"

    history_id = db.Column(db.Integer, primary_key=True)
    barangay_id = db.Column(db.Integer, db.ForeignKey("barangays.barangay_id"), nullable=False)
    month_start = db.Column(db.Date, nullable=False)
    food_packs = db.Column(db.Integer, nullable=False, default=0)
    affected_families = db.Column(db.Integer, nullable=False, default=0)
    event_count = db.Column(db.SmallInteger, nullable=False, default=0)
    max_event_severity = db.Column(db.SmallInteger, nullable=False, default=0)
    data_source = db.Column(db.String(20), nullable=False, default="synthetic")

    __table_args__ = (
        db.UniqueConstraint("barangay_id", "month_start", name="uq_history_barangay_month"),
        db.Index("ix_history_month", "month_start"),
    )
