"""
Renders a build_report() dict (see report_data.py) into a real PDF or Excel
file. One renderer per format, shared by every report type — the report data
already carries generic columns/rows, so no per-report-type layout code is
needed here.
"""
import io

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable

NAVY = colors.HexColor("#0f2547")
MUTED = colors.HexColor("#8a94a6")
LIGHT_GRAY = colors.HexColor("#f4f6fa")
BORDER = colors.HexColor("#e1e5eb")


def generate_pdf(report):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=0.6 * inch, bottomMargin=0.6 * inch,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("RLTitle", parent=styles["Title"], fontSize=16, textColor=NAVY, spaceAfter=2)
    eyebrow_style = ParagraphStyle("RLEyebrow", parent=styles["Normal"], fontSize=8, textColor=MUTED)
    body_style = ParagraphStyle("RLBody", parent=styles["Normal"], fontSize=9)
    note_style = ParagraphStyle("RLNote", parent=styles["Normal"], fontSize=9, leftIndent=10, spaceAfter=3)
    footer_style = ParagraphStyle("RLFooter", parent=styles["Normal"], fontSize=7, textColor=MUTED, alignment=TA_CENTER)

    story = [
        Paragraph("REPUBLIC OF THE PHILIPPINES", eyebrow_style),
        Paragraph("PROVINCE OF PANGASINAN &middot; PSWDO", eyebrow_style),
        Paragraph(report["title"], title_style),
        Spacer(1, 6),
    ]

    meta_rows = [
        ["Coverage:", report["coverage"], "Typhoon Event:", report["event_name"]],
        ["Municipality:", report["municipality_label"], "Prepared By:", report["prepared_by_role"]],
        ["Date Generated:", report["date_generated"].strftime("%B %d, %Y"), "System:", "ReliefLine v1.0"],
    ]
    meta_table = Table(meta_rows, colWidths=[80, 170, 80, 170])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), NAVY),
        ("TEXTCOLOR", (2, 0), (2, -1), NAVY),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story += [meta_table, Spacer(1, 4), HRFlowable(width="100%", color=BORDER), Spacer(1, 10)]

    if report["rows"]:
        col_count = len(report["columns"])
        col_width = doc.width / col_count
        wrapped_rows = [
            [Paragraph(str(cell), body_style) for cell in row] for row in report["rows"]
        ]
        header_cells = [Paragraph(f"<b>{c}</b>", ParagraphStyle("RLHead", parent=body_style, textColor=colors.white)) for c in report["columns"]]
        table = Table([header_cells] + wrapped_rows, colWidths=[col_width] * col_count, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(table)
    else:
        story.append(Paragraph("No records match the selected filters.", body_style))

    if report.get("notes"):
        story.append(Spacer(1, 14))
        story.append(Paragraph("NOTES", ParagraphStyle("RLNotesHead", parent=body_style, textColor=NAVY, fontName="Helvetica-Bold")))
        for note in report["notes"]:
            story.append(Paragraph(f"&bull; {note}", note_style))

    story.append(Spacer(1, 30))
    sig_col = doc.width / 3
    sig_table = Table([
        ["_" * 26, "_" * 26, "_" * 26],
        ["Prepared By", "Reviewed By", "Approved By"],
        [report["prepared_by_role"], "Provincial Social Welfare Officer IV", "Provincial Governor"],
    ], colWidths=[sig_col] * 3)
    sig_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 2), (-1, 2), MUTED),
        ("TOPPADDING", (0, 1), (-1, 1), 2),
    ]))
    story.append(sig_table)

    story.append(Spacer(1, 10))
    story.append(Paragraph(
        "Generated by ReliefLine — Data-Driven Food Pack Allocation System &middot; "
        f"Province of Pangasinan &middot; {report['date_generated'].strftime('%B %d, %Y')}",
        footer_style,
    ))

    doc.build(story)
    page_count = max(doc.page, 1)
    buffer.seek(0)
    return buffer.getvalue(), page_count


def generate_excel(report):
    wb = Workbook()
    ws = wb.active
    ws.title = report["title"][:31]

    title_font = Font(bold=True, size=14, color="0F2547")
    meta_font = Font(size=9, color="555555")
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="0F2547")

    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=max(len(report["columns"]), 2))
    ws.cell(row=1, column=1, value=report["title"]).font = title_font

    meta_lines = [
        f"Coverage: {report['coverage']}",
        f"Typhoon Event: {report['event_name']}",
        f"Municipality: {report['municipality_label']}",
        f"Date Generated: {report['date_generated'].strftime('%B %d, %Y')}",
        f"Prepared By: {report['prepared_by_role']}",
        "System: ReliefLine v1.0",
    ]
    row = 2
    for line in meta_lines:
        ws.cell(row=row, column=1, value=line).font = meta_font
        row += 1

    row += 1
    header_row = row
    for col_idx, col_name in enumerate(report["columns"], start=1):
        cell = ws.cell(row=header_row, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")

    for r_offset, data_row in enumerate(report["rows"], start=1):
        for c_idx, value in enumerate(data_row, start=1):
            ws.cell(row=header_row + r_offset, column=c_idx, value=value)

    for col_idx, col_name in enumerate(report["columns"], start=1):
        col_letter = get_column_letter(col_idx)
        cell_lens = [len(str(col_name))] + [len(str(r[col_idx - 1])) for r in report["rows"]]
        ws.column_dimensions[col_letter].width = min(max(max(cell_lens) + 2, 10), 40)

    if report.get("notes"):
        notes_row = header_row + len(report["rows"]) + 2
        ws.cell(row=notes_row, column=1, value="Notes").font = Font(bold=True, color="0F2547")
        for i, note in enumerate(report["notes"], start=1):
            ws.cell(row=notes_row + i, column=1, value=f"• {note}")

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    page_count = max(1, -(-len(report["rows"]) // 40))
    return buffer.getvalue(), page_count


def generate_file(report, fmt):
    if fmt == "pdf":
        return generate_pdf(report)
    if fmt == "excel":
        return generate_excel(report)
    raise ValueError(f"Unknown export format: {fmt}")
